version: '3'

x-minio-common: &minio-common
  image: quay.io/minio/minio:v1.0.0
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
  environment:
    MINIO_ROOT_USER: tiktokMinio
    MINIO_ROOT_PASSWORD: tiktokMinio
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  Etcd:
    image: 'bitnami/etcd:v1.0.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2380

  douyin-api:
    image: '1.12.68.184:5000/douyin-api-hertz:v1.0.0'
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    ports:
      - 8089:8089
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
      - 8086:8086

  douyin-rpc-commentsrv:
    image: '1.12.68.184:5000/douyin-rpc-commentsrv:v1.0.0'
    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config

  douyin-rpc-messagesrv:
    image: '1.12.68.184:5000/douyin-rpc-messagesrv:v1.0.0'
    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config

  douyin-rpc-relationsrv:
    image: '1.12.68.184:5000/douyin-rpc-relationsrv:v1.0.0'
    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config

  douyin-rpc-videosrv:
    image: '1.12.68.184:5000/douyin-rpc-videosrv:v1.0.0'
    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config

  douyin-rpc-usersrv:
    image: '1.12.68.184:5000/douyin-rpc-usersrv:v1.0.0'
    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config

  douyin-rpc-favoritesrv:
    image: '1.12.68.184:5000/douyin-rpc-favoritesrv:v1.0.0'

    network_mode: 'service:douyin-api'
    volumes:
      - type: bind
        source: ./config
        target: /app/config
